### ISSUE TITLE
sumologic-collector-puppet-module added to puppet forge ?

### ISSUE THREAD

**Issue by lreed** [SumoLogic/sumologic-collector-puppet-module#38]
Are there any plans to add the sumologic-collector-puppet-module to puppet forge.

I would like to start working with this module, but my company has systems to pull from the Forge.

Any chance we could get the last release added to puppet forge?  Or does anyone mind if I fork and add it to puppet forge?

Thanks in advance.

**Comment by arunpatyal** [comment]
The module is now available on puppet forge
